name: caching

on:
  workflow_dispatch:
    inputs:
        use-cache:
            description: 'Enable caching for node modules'
            type: boolean
            default: true
        node-version:
            description: 'Node.js version to setup'
            type: choice
            options:
              - '18.x'
              - '20.x'
              - '21.x'
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: '13-caching/react-app'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ inputs.node-version }}

            - name: Download cached dependencies
              uses: actions/cache@v3
              if: ${{ inputs.use-cache }}
              id: cache
              with:
                path: 13-caching/react-app/node_modules
                key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
            - name: install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm install
            - name: Run tests
              run: npm test
            - name: Build project
              run: npm run build
            - name: deploy to non prod
              run: echo "Deploying to non-prod environment"